name: Node
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: lint
        run: pnpm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: build
        run: pnpm run build
